### ISSUE TITLE
Flow for Git session tomorrow

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/sandbox#1]
Hey @mbonsma, you still up for doing the demo for the collaboration and conflict resolution for the git session tomorrow?

If so! I've put a short list/walkthrough, just so we have a reference to go by:

**Show collaboration (with Maddy)**
Set up repo in github (sandbox)
Both of us fork
Both clone
Both make changes to README
Both set upstream (git remote add upstream http to repo)
Both push, both pull request, I accept mine
Maddy pull from upstream
Look at changed file
Fix it, push up
Accept pull request
Done! :)

**Comment by QuLogic** [comment]
One thing that tripped up a lot of people last time is that they'd fall behind, and then when they tried to generate a conflict, they'd be starting with the latest version, so no conflicts would ever happen. It's probably a good idea to make sure everyone's on the same page at about that point.
